# -*- coding:utf-8 -*-
from django.conf import settings
from django.conf.urls import url
from django.views.static import serve

from .config import APP_NAME
from .views import address, activity, common, credits, coupon, invitation, lottery, map,\
    online_num_taking, promotion, reservation, register, signin, seller,\
    seller_registration_audit, seller_replace_audit, shop, signin, user


app_name = APP_NAME

urlpatterns = [
    url(r'^(?P<name>[\w]+)\.(?P<extension>[\w]+)$', common.favicon, name='rootfile'),
    url(r'^activity/$', activity.index, name='activity'),
    url(r'^activity/check$', activity.index_check, name='activity_check'),
    url(r'^address/get_region_json/$', address.get_region_json, name='address_get_region_json'),
    url(r'^address/modify/page/$', address.modify_page, name='address_modify_page'),
    url(r'^address/modify/$', address.modify, name='address_modify'),
    url(r'^common/fetch_openid/$', common.fetch_openid, name='fetch_openid'),
    url(r'^common/get_qrcode_str/$', common.get_qrcode_str, name='get_qrcode_str'),
    url(r'^common/send_vcode/$', common.send_vcode, name='send_vcode'),
    url(r'^common/check_vcode/$', common.check_vcode, name='check_vcode'),
    url(r'^time/data/$', common.get_server_time, name='time_data'),
    url(r'^coupon/page/$', coupon.page, name='coupon_page'),
    url(r'^coupon/invalid/page/$', coupon.invalid_page, name='coupon_invalid_page'),
    url(r'^coupon/trade/$', coupon.trade, name='coupon_trade'),
    url(r'^coupon/trade_reply/$', coupon.trade_reply, name='coupon_trade_reply'),
    url(r'^coupon/use/page/$', coupon.use_page, name='coupon_use_page'),
    url(r'^coupon/use/invalid/page/$', coupon.use_invalid_page, name='coupon_use_invalid_page'),
    url(r'^credits/history/page/$', credits.history_page, name='credits_history_page'),
    url(r'^credits/history/details/page/$', credits.history_details_page, name='credits_history_details_page'),
    url(r'^credits/page/$', credits.page, name='credits_page'),
    url(r'^credits/trade/$', credits.trade, name='credits_trade'),
    url(r'^credits/trade_reply/$', credits.trade_reply, name='credits_trade_reply'),
    url(r'^invitation/ranking/list/$', invitation.ranking_list, name='invitation_ranking_list'),
    url(r'^invitation/register/page/$', invitation.register_page, name='invitation_register_page'),
    url(r'^invitation/register_pre/$', invitation.register_pre, name='invitation_register_pre'),
    url(r'^invitation/register/$', invitation.register, name='invitation_register'),
    url(r'^invitation/coupon_pre/$', invitation.coupon_pre, name='invitation_coupon_pre'),
    url(r'^invitation/coupon/$', invitation.coupon, name='invitation_coupon'),
    url(r'^lottery/page/$',lottery.lottery_page, name='lottery_page'),
    url(r'^lottery/submit/$',lottery.lottery_submit, name='lottery_submit'),
    url(r'^lottery/details/$',lottery.lottery_detail, name='lottery_details'),
    url(r'^lottery/set/$',lottery.lottery_set, name='lottery_set'),
    url(r'^lottery/details/message/$',lottery.lottery_page, name='lottery_details_message'),
    url(r'^map/branch/data/$', map.branch_data, name='map_branch_data'),
    url(r'^map/page/$', map.page, name='map_page'),
    url(r'^online/num/taking/page/$', online_num_taking.page, name='online_num_taking_page'),
    url(r'^online/num/taking/submit/$', online_num_taking.submit, name='online_num_taking_submit'),
    url(r'^online/num/taking/waitman/$', online_num_taking.waitman, name='online_num_taking_submit'),
    url(r'^online/num/taking/status/page/$', online_num_taking.status_page, name='online_num_taking_status_page'),
    url(r'^online/num/taking/status/list/$', online_num_taking.status_list, name='online_num_taking_status_list'),
    url(r'^promotion/page/$', promotion.page, name='promotion_page'),
    url(r'^promotion/all/page/$', promotion.all_page, name='promotion_all_page'),
    url(r'^promotion/details/page/$', promotion.details_page, name='promotion_details_page'),
    url(r'^promotion/details/order_term_check/$', promotion.order_term_check, name='promotion_details_check'),
    url(r'^promotion/order/page/$', promotion.order_page, name='promotion_order_page'),
    url(r'^promotion/purchase/$', promotion.purchase, name='promotion_purchase'),
    url(r'^reservation/etc/page/$', reservation.reservation_ETC_page, name='reservation_etc_page'),
    url(r'^reservation/etc/submit/$', reservation.reservation_ETC, name='reservation_etc_submit'),
    url(r'^reservation/open/account/page/$', reservation.reservation_open_account_page, name='reservation_open_account_page'),
    url(r'^reservation/open/account/submit/$', reservation.reservation_open_account, name='reservation_open_account_submit'),
    url(r'^reservation/withdrawal/page/$', reservation.reservation_withdrawal_page, name='reservation_withdrawal_page'),
    url(r'^reservation/withdrawal/submit/$', reservation.reservation_withdrawal, name='reservation_withdrawal_submit'),
    url(r'^reservation/num/taking/page/$', reservation.reservation_num_taking_page, name='reservation_num_taking_page'),
    url(r'^reservation/num_taking/submit/$', reservation.reservation_num_taking, name='reservation_num_taking_submit'),
    url(r'^reservation/loan/page/$', reservation.reservation_loan_page, name='reservation_loan_page'),
    url(r'^reservation/loan/submit/$', reservation.reservation_loan, name='reservation_loan_submit'),
    url(r'^reservation/kdd/index/$', reservation.kdd_index, name='reservation_kdd_index'),
    url(r'^reservation/kdd/page/$', reservation.kdd_page, name='reservation_kdd_page'),
    # url(r'^reservation/kdd/param/$', reservation.kdd_param, name='reservation_kdd_param'),
    url(r'^reservation/kdd/search/$', reservation.kdd_search, name='reservation_kdd_search'),
    url(r'^reservation/kdd/submit/$', reservation.kdd_submit, name='reservation_kdd_submit'),
    url(r'^reservation/dgkh/page/$', reservation.dgkh_page, name='reservation_dgkh_page'),
    url(r'^reservation/dgkh/nearest_branch/$', reservation.dgkh_nearest_branch, name='reservation_dgkh_nearest_branch'),
    url(r'^reservation/dgkh/submit/$', reservation.dgkh_submit, name='reservation_dgkh_submit'),
    url(r'^reservation/status/list/$', reservation.reservation_status_list, name='reservation_status_list'),
    url(r'^reservation/deal/list/$', reservation.reservation_deal_list, name='reservation_deal_list'),
    url(r'^reservation/deal/submit/$', reservation.reservation_deal_submit, name ='reservation_deal_submit'),
    url(r'^register/page/$', register.page, name='register_page'),
    url(r'^register/protocol/$', register.get_protocol, name='register_protocol'),
    url(r'^register/user/$', register.user_register, name='register_user'),
    url(r'^register/seller/$', register.seller_register, name='register_seller'),
    url(r'^register/seller/audit/page/$', seller_registration_audit.page, name='register_seller_audit_page'),
    url(r'^register/seller/audit/head_admin/$', seller_registration_audit.head_admin, name='register_seller_audit_for_head_admin'),
    url(r'^register/seller/audit/branch_admin/$', seller_registration_audit.branch_admin, name='register_seller_audit_for_branch_admin'),
    url(r'^register/seller/audit/client_manager/$', seller_registration_audit.client_manager, name='register_seller_audit_for_client_manager'),
    url(r'^register/shop/page/$', register.seller_register2_page, name='register_shop_page'),
    url(r'^register/shop/submit/$', register.seller_register2, name='register_shop_submit'),
    url(r'^seller/account_modify/$', seller.account_modify, name='seller_account_modify'),
    url(r'^seller/info/$', seller.info, name='seller_info'),
    url(r'^seller/list/page/$', seller.cooperative_seller_page, name='seller_list_page'),
    url(r'^seller/list/(?P<type_id>[0-9]{1,2})/$', seller.seller_list, name='seller_list_typed'),
    url(r'^seller/page/$', seller.seller_page, name='seller_page'),
    url(r'^seller/parse_qrcode_str/$', seller.parse_qrcode_str, name='seller_parse_qrcode_str'),
    url(r'^seller/withdraw_apply/page/$', seller.withdraw_apply_page, name='seller_withdraw_apply_page'),
    url(r'^seller/withdraw_apply/$', seller.withdraw_apply, name='seller_withdraw_apply'),
    url(r'^seller/withdraw_status/page/$', seller.withdraw_status_page, name='seller_withdraw_status_page'),
    url(r'^seller_replace/audit/page/$', seller_replace_audit.page, name='seller_replace_audit_page'),
    url(r'^seller_replace/audit/head_admin/$', seller_replace_audit.head_admin, name='seller_replace_audit_for_head_admin'),
    url(r'^seller_replace/audit/branch_admin/$', seller_replace_audit.branch_admin, name='seller_replace_audit_for_branch_admin'),
    url(r'^seller_replace/audit/client_manager/$', seller_replace_audit.client_manager, name='seller_replace_audit_for_client_manager'),
    url(r'^seller_replace/audit/recheck/$', seller_replace_audit.recheck, name='seller_replace_audit_recheck'),
    url(r'^shop/name_modify/$', shop.name_modify, name='shop_name_modify'),
    url(r'^shop/page/$', shop.shop_page, name='shop_page'),
    url(r'^shop/photo/$', shop.photo, name='shop_photo'),
    url(r'^shop/seller_replace_query/$', shop.seller_replace_query, name='shop_seller_replace_query'),
    url(r'^shop/seller_replace_apply/$', shop.seller_replace_apply, name='shop_seller_replace_apply'),
    url(r'^sign/page/$',signin.sign_page, name='sign_page'),
    url(r'^sign/get/signin/$',signin.get_signin, name='sign_get_signin'),
    url(r'^sign/signin/$',signin.signin, name='sign_signin'),
    url(r'^staticfile/(?P<name>[a-z_\d]+)/$', common.static, name='staticfile'),
    url(r'^user/binding/$', user.binding, name='user_binding'),
    url(r'^user/get_user/$', user.get_user, name='user_get'),
    url(r'^user/info/page/$', user.info_page, name='user_info_page'),
    url(r'^user/photo/$', user.photo, name='user_photo'),
    url(r'^user/parse_qrcode_str/', user.parse_qrcode_str, name='user_parse_qrcode_str'),
    url(r'^user/payment_password/fetch/$', user.payment_password_fetch, name='user_payment_password_fetch'),
    url(r'^user/payment_password/modify/page/$', user.payment_password_modify_page, name='user_payment_password_modify_page'),
    url(r'^user/modify/payment_password/$', user.payment_password_modify, name='user_modify_payment_password'),
    url(r'^user/payment_password/verify/$', user.payment_password_verify, name='user_payment_password_verify'),
    url(r'^wx/jssdk/$', common.jssdk, name='wx_jssdk'),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,}),
]
